server:
  port: 8080
spring:
  application:
    name: http-test-server
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# eureka客户端配置
eureka:
  client:
    service-url:                                    # 服务注册的请求地址
      defaultZone: http://admin:123456@localhost:8761/eureka/